version: "3.9" # optional since v1.27.0
services:
  db:
    image: mysql:8.0.23
    platform: linux/amd64
    volumes:
      - /var/data/mysql:/var/lib/mysql
      - /etc/mysql:/etc/mysql
      - ./mysql-files:/var/lib/mysql-files
    restart: always
    environment:
      MYSQL_DATABASE: 'root'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root123'
    ports:
      - "3308:3306"
volumes:
  .:
  logvolume01: {}
